[project]
name = "genai-backend"
version = "0.1.0"
description = ""
authors = [
    {name = "Naveen Meena",email = "naveen@Naveens-MacBook-Air.local"}
]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "fastapi (>=0.121.2,<0.122.0)",
    "uvicorn (>=0.38.0,<0.39.0)",
    "python-dotenv (>=1.2.1,<2.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "openai (>=2.8.1,<3.0.0)"
]

[tool.poetry]
packages = [{include = "genai_backend", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
